### ISSUE TITLE
Hi Andrezj 

### ISSUE THREAD

**Issue by megaluck** [fullstack-guru0719/fullstack-guru0719#1]
Hi Andrezj it´s Gustavo from freelancer, please send me a email to gustavo.fialho@gmail.com So I can setup a call on Monday

**Comment by fullstack-guru0719** [comment]
Thank  you .
I hope to talk with you soon.
This is my information. 

mousesnake9@gmail.com
https://t.me/JerDev0719
whatsapp: +12294997787
phone: +12543261334
live:.cid.f2d1d4834e1229fe
https://github.com/fullstack-guru0719


Have a nice weekend.

**Comment by fullstack-guru0719** [comment]
Hi
I want to talk with you via telegram, whatsapp, skype, gmali...

**Comment by megaluck** [comment]
Hey Andrezj sent you a message on telegram, couldnt add your contact on whatsapp
